# Generated by Django 4.2.4 on 2023-08-18 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_product_date_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_date',
        ),
    ]
